### PR TITLE
Add functionality to connect form to GitHub repo

### LINKED ISSUE #6: create new branch for user to push to
After user is authenticated, try to create a new branch on the target repo. The app will push to this branch on user's behalf.

### Get the SHA of master branch*
GET `https://api.github.com/repos/:USER/:REPO/git/ref/heads/master`

### Start new branch off master
POST `https://api.github.com/repos/:USER/:REPO/git/refs`, body:
```JSON
{
  "ref": "refs/heads/Publiccode-Pusher/add-publiccode-yml",
  "sha": "{ SHA of master branch from previous step }"
}
```
Gist [here](https://gist.github.com/potherca/3964930)

Note that this endpoint only accepts JSON, and some kind of special GitHub JSON `application/vnd.github+json`. Docs here https://developer.github.com/v3/git/refs/

You'll get back a response like
```JSON
{
  "ref": "refs/heads/add-publiccode-yaml",
  "node_id": "MDM6UmVmMjEzMTEzODcwOmFkZC1wdWJsaWNjb2RlLXlhbWw=",
  "url": "https://api.github.com/repos/ckingbailey/publiccode-pusher/git/refs/heads/add-publiccode-yaml",
  "object": {
    "sha": "6839f3114250a180a948ff3dc52689241de45a2f",
    "type": "commit",
    "url": "https://api.github.com/repos/ckingbailey/publiccode-pusher/git/commits/6839f3114250a180a948ff3dc52689241de45a2f"
  }
}
```
Hold onto that SHA. You'll need it to push the publiccode.yml to our new branch.

If you get a "403 Forbidden" or the like then the user doesn't have sufficient permissions on the target repo. I haven't tried this on a repo I don't have access to yet so I don't know what exactly that response will look like. If the user lacks permissions then we resort to strategies outlined in issue #3 

\* If repo has no master branch, or is not called master branch, that's too complicated for this app to handle at this point

### PR DESCRIPTION
**Pull request by ckingbailey**
Resolves #6 

This PR deviates slightly from the issue it resolves.

Instead of pushing a new branch to the target repo as a way to test the user's permission, I'm using the GH API endpoint that is for querying the permissions of collaborators. We will still need to push a new branch, but only once the user submits the form to PR the publiccode.yml file.

This PR also changes the browser storage used from localStorage to sessionStorage. This means the GH access token and target repo are deleted when the window is closed.

#### Adds a field to the login form taking a URL of a GitHub repo
Screen Shot 2020-02-22 at 9 48 58 PM

#### When user logs in, app uses the GitHub API endpoint /:owner/:repo/collaborators/:user/permission to test the user's permission (read, write, admin, etc) on the target repo.
If they don't have write permission or higher, keep them logged in and show a message letting them know they don't have sufficient permissions. Show the field again to choose a new repo
Screen Shot 2020-02-22 at 9 49 25 PM

#### If they have write or higher permission, show the form with the repo specified in the heading, and a button to go back and connect to a different repo
Screen Shot 2020-02-22 at 9 49 46 PM

#### Click the "Connect to a different repo" button to go back to the repo entry field
Screen Shot 2020-02-22 at 9 50 15 PM

### CODE REVIEW

**Comment by plocket** [comment]
I'll keep looking over the files, but is there a reason to deviate from the UX design we've already established? This might be easier to has out real-time.

**Comment by ckingbailey** [comment]
What about this deviates from the established UX design?

**Comment by plocket** [comment]
Unauthorized repo behaved as expected.

**Comment by ckingbailey** [comment]
> * Tried 'Push to GitHub'. Got success message immediately, but **I don't see a PR here**.

That's not what this PR does. This new stuff added by this PR is only to check the user's permission level on the target repo.

**Pull request merged**
