### PR TITLE
Wire up form to push YAML file to GitHub

### PR DESCRIPTION
**Pull request by ckingbailey**
🎉 Yay it works

The crux of this PR is that it changes the submit handler of the editor form to push a publiccode.yml file to the target repo and open a pull request to add that file.

Some stuff that goes along with this change:
- Success notification is a lot bigger, and green
- Error notifications are a little more descriptive
- Submit goes disabled & grey while app is doing its work of pushing branch and opening PR

Some bonus work:
- Make login form an actual form, instead of using an anchor element
- Start to put colors into named variables in a file `color.scss`
- Start to delete unused or commented-out code

There's a lot left to be desired here, which I have or will open issues for, such as replacing the annoying notifier library with something better.

Much of this work is subject to change in the near future per our conversation with the rest of the team. However, the core functionality of the app is delivered by this PR.

### CODE REVIEW

**Comment by plocket** [comment]
> The crux of this PR is that it changes the submit handler of the editor form to push a publiccode.yml file to the target repo and open a pull request to add that file.

Do you mean "to push a publiccode.yml file to a new branch on the target repo"? Is that the change?

**Review by plocket — APPROVED** [review]
Worked for me!

An issue to add: When I tried to copy the url for looking at the pull request, I click-dragged to highlight. When I lifted my mouse, the modal disappeared and I couldn't copy the text. My suggestion is 1. to make that a link instead of just text and 2. to only disappear it when someone click on an 'x' in the top left. We might want to get an experienced UX perspective on that flow, though.

**Comment by ckingbailey** [comment]
Yeah, I realize that notifier is terrible. It’s a library, ReactNotifier, that was already in use throughout the form. There’s an issue open to replace it with something better.

I used the existing notifier because the redux actions & reducers to add/remove notifications are already in place. My hope is that we can preserve to existing actions & reducers while replacing that crappy UI.

**Comment by plocket** [comment]
Got it. This is ready for merging, btw.

**Pull request merged**
